Che ping/kinmen/feat dr bid page
NCKU-CCS/energy-frontend-v2 pull request #35
Opened 2021-01-22 16:11 UTC by curry0622

- Create fake data
- User is able to choose a date to change data
- `Status` showing total dr volume and total price
- List prototype
- RWD done
- i18n done

2021-01-26 07:11 UTC, coliver0221 requested changes
I think it's not necessary to separate `drBidPage/status` into main and sub components since there is only one sub-component.
It's fine to just have `drBidPage/status/index.tsx`.

2021-01-26 07:11 UTC, coliver0221 commented on src/components/drBidPage/submit/typeButton.tsx
> +        {t('drbidpage.day')}
I think `.dayAhead` is more clear to understand.

2021-01-26 09:43 UTC, curry0622 commented on src/components/drBidPage/submit/typeButton.tsx
> +        {t('drbidpage.day')}
Done. Thx

2021-01-26 09:46 UTC, coliver0221 commented
Please fix the conflict, thanks.

2021-01-27 02:03 UTC, coliver0221 approved these changes

2021-01-27 02:05 UTC, coliver0221 commented
LGTM, thanks.

2021-01-27 02:05 UTC, merged